version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION_ARN>"  # will be replaced dynamically
        LoadBalancerInfo:
          ContainerName: "khaleel-strapi-container"
          ContainerPort: 1337